<?php
$title = 'Nueva empresa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the nombre element:
$nombre = $form->get('nombre');
$nombre->setAttribute('class', 'form-control');
$nombre->setAttribute('placeholder', 'Nombre de la empresa');

// This provides a default CSS class and placeholder text for the descripcion element:
$descripcion = $form->get('descripcion');
$descripcion->setAttribute('class', 'form-control');
$descripcion->setAttribute('placeholder', 'Descripción sobre la empresa');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('empresas', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($nombre) ?>
    <?= $this->formElement($nombre) ?>
    <?= $this->formElementErrors()->render($nombre, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($descripcion) ?>
    <?= $this->formElement($descripcion) ?>
    <?= $this->formElementErrors()->render($descripcion, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();